server:
  port: 8080

spring:
  application:
    name: recaudosoap

wsdl:
  address: "http://localhost:8080/InsitelCollectionServicePse/wsdl"

api:
  clients:
    verification:
      url: "https://pruebados.bitwan.info/recaudo/verificacion"
      auth:
        type: basic
        username: ${PSE_API_USER}
        password: ${PSE_API_PASS}

    payment:
      url: "https://pruebados.bitwan.info/recaudo/notificacion-pago"
      auth:
        type: basic
        username: ${PSE_API_USER}
        password: ${PSE_API_PASS}

    confirmation-pse:
      url: "https://pruebados.bitwan.info/recaudo/pse-rest/notificacion-pago"
      auth:
        type: basic
        username: ${PSE_API_USER}
        password: ${PSE_API_PASS}

    otra-api:
      url: "https://ejemplo.com/otra-api"
      auth:
        type: none
