api:
  clients:
    verification:
      url: "https://pruebados.bitwan.info/recaudo/verificacion"
      auth:
        type: basic
        username: "pse.api-access"
        password: "PSE_4P1_ACC3S5"

    payment:
      url: "https://pruebados.bitwan.info/recaudo/notificacion-pago"
      auth:
        type: basic
        username: "pse.api-access"
        password: "PSE_4P1_ACC3S5"

    confirmation-pse:
      url: "https://pruebados.bitwan.info/recaudo/pse-rest/notificacion-pago"
      auth:
        type: basic
        username: "pse.api-access"
        password: "PSE_4P1_ACC3S5"    

    otra-api:
      url: "https://ejemplo.com/otra-api"
      auth:
        type: none
