spring.application.name=recaudosoap
spring.config.import=optional:file:.env[.properties]
#server.servlet.contextPath=/InsitelCollectionServicePse
#SERVICE_URL=http://localhost:8080/InsitelCollectionServicePse/wsdl3