<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:s="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://www.achcolombia.com.co/PSEHostingInvoicesWS"
    xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
    xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
    targetNamespace="http://www.achcolombia.com.co/PSEHostingInvoicesWS">

  <wsp:Policy wsu:Id="UTPolicy">
    <sp:SignedSupportingTokens>
      <wsp:Policy>
        <sp:UsernameToken
          sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient"/>
        <sp:WssUsernameToken10/>
      </wsp:Policy>
    </sp:SignedSupportingTokens>
  </wsp:Policy>

  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://www.achcolombia.com.co/PSEHostingInvoicesWS">

      <!-- Tipos auxiliares -->
      <s:complexType name="CommerceField">
        <s:sequence>
          <s:element name="Name" type="s:string" minOccurs="0"/>
          <s:element name="Value" type="s:string" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="ArrayOfCommerceField">
        <s:sequence>
          <s:element name="CommerceField" type="tns:CommerceField" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Factura confirmada -->
      <s:complexType name="InvoiceConfirmField">
        <s:sequence>
          <s:element name="InvoiceID" type="s:string"/>
          <s:element name="PaymentDescription" type="s:string"/>
          <s:element name="Amount" type="s:decimal"/>
          <s:element name="VatAmount" type="s:decimal"/>
          <s:element name="ExpirationDate" type="s:dateTime"/>
          <s:element name="ServiceCode" type="s:string"/>
          <s:element name="BankProcessDate" type="s:dateTime"/>
          <s:element name="TransactionState" type="s:string"/>
          <s:element name="TicketID" type="s:string"/>
          <s:element name="PaymentID" type="s:string"/>
          <s:element name="financialInstitutionCode" type="s:string"/>
          <s:element name="FinancialInstitutionName" type="s:string"/>
          <s:element name="TrazabilityCode" type="s:string"/>
          <s:element name="CycleID" type="s:int"/>
          <s:element name="ReferenceNumber1" type="s:string"/>
          <s:element name="ReferenceNumber2" type="s:string"/>
          <s:element name="ReferenceNumber3" type="s:string"/>
          <s:element name="PaymentAmount" type="s:decimal"/>
          <s:element name="ChargeAmount" type="s:decimal"/>
          <s:element name="Fields" type="tns:ArrayOfCommerceField" minOccurs="0"/>
        </s:sequence>
      </s:complexType>

      <s:complexType name="ArrayOfInvoiceConfirmField">
        <s:sequence>
          <s:element name="InvoiceConfirmField" type="tns:InvoiceConfirmField" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <!-- Solicitud de consulta -->
      <s:element name="GetTransactionInformationInvoice">
        <s:complexType>
          <s:sequence>
            <s:element name="TicketOfficeID" type="s:int"/>
            <s:element name="TKOPassword" type="s:string"/>
            <s:element name="QueryID" type="s:string"/>
            <s:element name="Customer_Password" type="s:string"/>
            <s:element name="rowID" type="s:int"/>
            <s:element name="paymentAmount" type="s:decimal"/>
            <s:element name="ChargeAmount" type="s:decimal"/>
            <s:element name="Email" type="s:string"/>
            <s:element name="CustomerIP" type="s:string"/>
            <s:element name="SoliciteDate" type="s:dateTime"/>
            <s:element name="Fields" type="tns:ArrayOfCommerceField" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- Respuesta de consulta -->
      <s:complexType name="GetTransactionInformationInvoiceResponse">
        <s:sequence>
          <s:element name="ReturnCode" type="s:string"/>
          <s:element name="ErrorMessage" type="s:string" minOccurs="0"/>
          <s:element name="InvoiceField" type="s:string" minOccurs="0" maxOccurs="unbounded"/>
        </s:sequence>
      </s:complexType>

      <s:element name="GetTransactionInformationInvoiceResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="GetTransactionInformationInvoiceResult" type="tns:GetTransactionInformationInvoiceResponse" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <!-- Confirmación de pago -->
      <s:element name="ConfirmTransactionPaymentInvoice">
        <s:complexType>
          <s:sequence>
            <s:element name="TicketOfficeID" type="s:int"/>
            <s:element name="TKOPassword" type="s:string"/>
            <s:element name="rowID" type="s:int"/>
            <s:element name="Invoices" type="tns:ArrayOfInvoiceConfirmField"/>
          </s:sequence>
        </s:complexType>
      </s:element>

      <s:element name="ConfirmTransactionPaymentInvoiceResponse">
        <s:complexType>
          <s:sequence>
            <s:element name="ReturnCode" type="s:string"/>
            <s:element name="Optional" type="s:string" minOccurs="0"/>
          </s:sequence>
        </s:complexType>
      </s:element>

    </s:schema>
  </wsdl:types>

  <!-- Mensajes -->
  <wsdl:message name="GetTransactionInformationInvoiceRequest">
    <wsdl:part name="parameters" element="tns:GetTransactionInformationInvoice"/>
  </wsdl:message>
  <wsdl:message name="GetTransactionInformationInvoiceResponse">
    <wsdl:part name="parameters" element="tns:GetTransactionInformationInvoiceResponse"/>
  </wsdl:message>
  <wsdl:message name="ConfirmTransactionPaymentInvoiceRequest">
    <wsdl:part name="parameters" element="tns:ConfirmTransactionPaymentInvoice"/>
  </wsdl:message>
  <wsdl:message name="ConfirmTransactionPaymentInvoiceResponse">
    <wsdl:part name="parameters" element="tns:ConfirmTransactionPaymentInvoiceResponse"/>
  </wsdl:message>

  <!-- Operaciones -->
  <wsdl:portType name="PSEHostingInvoicesWSSoap">
    <wsdl:operation name="GetTransactionInformationInvoice">
      <wsdl:input message="tns:GetTransactionInformationInvoiceRequest"/>
      <wsdl:output message="tns:GetTransactionInformationInvoiceResponse"/>
    </wsdl:operation>
    <wsdl:operation name="ConfirmTransactionPaymentInvoice">
      <wsdl:input message="tns:ConfirmTransactionPaymentInvoiceRequest"/>
      <wsdl:output message="tns:ConfirmTransactionPaymentInvoiceResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <!-- Binding -->
  <wsdl:binding name="PSEHostingInvoicesWSSoap" type="tns:PSEHostingInvoicesWSSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <wsp:PolicyReference URI="#UTPolicy"/>
    <wsdl:operation name="GetTransactionInformationInvoice">
      <soap:operation soapAction="https://pruebados.bitwan.info/InsitelCollectionServicePse/GetTransactionInformationInvoice" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ConfirmTransactionPaymentInvoice">
      <soap:operation soapAction="https://pruebados.bitwan.info/InsitelCollectionServicePse/ConfirmTransactionPaymentInvoice" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <!-- Servicio y puertos -->
  <wsdl:service name="PSEHostingInvoicesWS">
    <wsdl:port name="PSEHostingInvoicesWSSoap" binding="tns:PSEHostingInvoicesWSSoap">
     <soap:address location="${SERVICE_URL}"/>
      <!--
      <soap:address location="http://localhost:8080/InsitelCollectionServicePse"/>
      <soap:address location="http://localhost:8080/InsitelCollectionServicePse/wsdl"/>
      <soap:address location="https://pruebados.bitwan.info/InsitelCollectionServicePse/wsdl"/>
      <soap:address location="${soap.address.location}"/>
      -->
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
